apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - typesensecluster.yaml

commonLabels:
  app.kubernetes.io/name: space-${META_NAME}
  app.kubernetes.io/component: docusaurus
  app.kubernetes.io/part-of: space-${META_NAME}